# Generated by Django 4.1 on 2023-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('besoin_eau', models.SmallIntegerField(blank=True, null=True)),
                ('besoin_soleil', models.SmallIntegerField(blank=True, null=True)),
                ('saison', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'produit',
                'managed': True,
            },
        ),
    ]
