# Generated by Django 4.1 on 2023-03-02 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='besoin_eau',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='besoin_soleil',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produit')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
            options={
                'db_table': 'selection',
                'managed': True,
            },
        ),
    ]
