# Generated by Django 4.1 on 2023-03-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_produit_saison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'evenement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.CharField(blank=True, max_length=15, null=True)),
                ('date_fin', models.CharField(blank=True, max_length=15, null=True)),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.evenement')),
                ('id_climat', models.ForeignKey(blank=True, db_column='id_climat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.climat')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produit')),
            ],
            options={
                'db_table': 'planning',
                'managed': True,
            },
        ),
    ]
