# Generated by Django 4.1 on 2023-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_evenement_planning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='id_climat',
            new_name='climat',
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_deb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
