# Generated by Django 4.1 on 2023-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_planning_date_deb_alter_planning_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date_fin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
