# Generated by Django 4.1 on 2023-03-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_astuce_selection_astuces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='astuces',
        ),
    ]
