# Generated by Django 4.1 on 2023-03-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_selection_astuces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astuce',
            name='image',
        ),
    ]
