# Generated by Django 4.1 on 2023-03-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_astuce_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Astuce',
        ),
    ]
