# Generated by Django 4.1 on 2023-03-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_astuce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('contenu', models.CharField(blank=True, max_length=500, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.produit')),
            ],
            options={
                'db_table': 'astuce',
                'managed': True,
            },
        ),
    ]
