# Generated by Django 4.1 on 2023-03-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_astuce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astuce',
            name='produit',
            field=models.ForeignKey(blank=True, db_column='id_produit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.produit'),
        ),
    ]
