# Generated by Django 4.1 on 2023-03-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_astuce_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astuce',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produit'),
        ),
    ]
