# Generated by Django 4.1 on 2023-03-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_astuce_produit_astuce_id_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astuce',
            name='id_produit',
        ),
    ]
