# Generated by Django 4.1 on 2023-03-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_astuce_id_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Astuce',
        ),
    ]
