# Generated by Django 4.1 on 2023-03-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_astuce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produit')),
            ],
            options={
                'db_table': 'conseil',
                'managed': True,
            },
        ),
    ]
