# Generated by Django 4.1 on 2023-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_conseil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date_deb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
