# Generated by Django 4.1 on 2023-03-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_planning_date_deb_alter_planning_date_fin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
