# Generated by Django 4.1 on 2023-03-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_delete_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('climat', models.ForeignKey(blank=True, db_column='id_climat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.climat')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.evenement')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.produit')),
            ],
            options={
                'db_table': 'planning',
                'managed': True,
            },
        ),
    ]
