# Generated by Django 4.1 on 2023-03-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
