# Generated by Django 4.1 on 2023-03-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_conseil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseil',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
